### ISSUE TITLE
Misc.issues

### ISSUE THREAD

**Issue by AkyV** [MontyTRC89/Tomb-Editor-Issues#8]
- "Locked" remark is the same as of "Wind".
- Rain, Snow, Quicksand intensity - where to set it?
- Level Settings/Game Version - "TRNG" doesn't seem to be saved for the next launch.
- TRNG triggers:
a, FMV has no parameter list
b, OldFlip Flipeffects also have problems with parameters list. Eg. if it says it needs & parameter, there is no & parameter. It also points to other issues, like:  "check all fields" for script code, even when I cannot adjust other fields / or wrong script code sometimes for them.
c, "Find Trigger" and "Export AnimCommands" TRNG trigger features are still missing.

**Comment by MontyTRC89** [comment]
1) Fixed in next update 1.0.5
2) Under Room Type ;)
3) It is a level setting, not a global setting
4) We are discussing about those issues

**Comment by AkyV** [comment]
2. Understood. :) However,  only "Water" has this property there. :) "Normal, Water1, Water2, Water3, Water4, Rain, Snow, Quicksand".
3. Yes, this is the way I did, however, it isn't saved. :)

**Comment by MontyTRC89** [comment]
2. Aaah I understand now. I'm still trying to understand this from original NGLE. I will investigate and try to solve this for update 1.0.5.

**Comment by ActuallyaDeviloper** [comment]
I am unable to reproduce 3.
I opened a new project changed and changed the game version in the level settings to TRNG. After closing the editor and reloading the saved file, the game version is still set to TRNG.

**Comment by MontyTRC89** [comment]
2. Fixed in 1.0.5 :)

**Comment by AkyV** [comment]
@ActuallyaDeviloper:
Perhaps that's what matters. I mean, I didn't do anything. Just adjusted TRNG, clicked Apply, OK, then re-launched the editor, and it said TR4 again. However, it is still an issue, right? :)

**Comment by ActuallyaDeviloper** [comment]
From your description I am reading that you are still confused about it being an editor wide setting. This is _not_ the case. The setting is instead stored in _each level_ file because you may want to create and work on both TR4 and TRNG levels (or maybe another level creator sends his files) and they are expected to work immediately without reconfiguring the editor for another engine.
If you create a new level (by opening the editor you get a new level), then you have _not_ configured it yet to be working for the TRNG engine, instead it is still targeting the default version.

It could now be argued that TRNG is supposed to be the default for new projects, however this is a different question and is not related to any level setting saving issues.

**Comment by AkyV** [comment]
Thank you for your answer. Now I understand. :)
Yes, in the future, you may add the chance to the users to adjust the default settings. But, you are right, it is something else,

**Comment by ActuallyaDeviloper** [comment]
Fixed the definition of old flips.

**Comment by AkyV** [comment]
Will they be there in the next update? Cool.

**Comment by ActuallyaDeviloper** [comment]
Yes. If you are curious....
[Editor.zip](https://github.com/MontyTRC89/Tomb-Editor-Issues/files/1653881/Editor.zip)

**Comment by AkyV** [comment]
Okay, I don't know exactly whereto copy/place it, so just quote a part:

>     <Subtrigger K="30" V="OldFlip. (?) Force Von Croy to reach &lt;&amp;&gt;AI_FOLLOW OCB when ???">
>       <Timer>
>         <AnyNumber />
>       </Timer>

So is this means eg. this trigger will work successfully? :)
